//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kiosk.Properties
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((object.ReferenceEquals(resourceMan, null)))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kiosk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static System.Drawing.Bitmap Cafe_Latte
        {
            get
            {
                object obj = ResourceManager.GetObject("Cafe Latte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Brand_HiveMark
        {
            get
            {
                object obj = ResourceManager.GetObject("Brand_HiveMark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap pictureBoxCoffee
        {
            get
            {
                object obj = ResourceManager.GetObject("pictureBoxCoffee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap keisuke2
        {
            get
            {
                object obj = ResourceManager.GetObject("keisuke2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ICON
        {
            get
            {
                object obj = ResourceManager.GetObject("ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap header
        {
            get
            {
                object obj = ResourceManager.GetObject("header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap keisuke1
        {
            get
            {
                object obj = ResourceManager.GetObject("keisuke1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap cafeLatte
        {
            get
            {
                object obj = ResourceManager.GetObject("cafeLatte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap cafeLatte1
        {
            get
            {
                object obj = ResourceManager.GetObject("cafeLatte1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap americano
        {
            get
            {
                object obj = ResourceManager.GetObject("americano", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap hazelnutAmericano
        {
            get
            {
                object obj = ResourceManager.GetObject("hazelnutAmericano", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_BeefTapa
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_BeefTapa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_BakedBangus
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_BakedBangus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_CaramelizedChicken
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_CaramelizedChicken", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_GiantPorkTonkatsu
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_GiantPorkTonkatsu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_HamAndEgg
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_HamAndEgg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_Hungarian
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_Hungarian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Pay_GcashQr
        {
            get
            {
                object obj = ResourceManager.GetObject("Pay_GcashQr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_Americano
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_Americano", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_GreenteaAppleade
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_GreenteaAppleade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_BananaMalt
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_BananaMalt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_BelgianCocoa
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_BelgianCocoa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_BerryBanana
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_BerryBanana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_BerryMalt
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_BerryMalt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_CafeLatte
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_CafeLatte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_CaramelMacchiato
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_CaramelMacchiato", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_ChocoHazelnut
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_ChocoHazelnut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_ChocoMalt
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_ChocoMalt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_CinnamonOatmilkLatte
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_CinnamonOatmilkLatte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_CookiesAndCream
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_CookiesAndCream", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_CafeCreamBerry
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_CafeCreamBerry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_CafeCreamMocha
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_CafeCreamMocha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_DarkChocoMilkTea
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_DarkChocoMilkTea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_FraiseStrawberry
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_FraiseStrawberry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_HazelnutAmericano
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_HazelnutAmericano", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_IrishCreamCafeLatte
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_IrishCreamCafeLatte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_TraditionalMatcha
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_TraditionalMatcha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_OkinawaBrownSugarMilkTea
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_OkinawaBrownSugarMilkTea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_PassionFruit
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_PassionFruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_PearlMilkTea
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_PearlMilkTea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_RedVelvet
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_RedVelvet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_SpanishLatte
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_SpanishLatte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_TaroMilkTea
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_TaroMilkTea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_MatchaCheesecake
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_MatchaCheesecake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_WinterMelonMilkTea
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_WinterMelonMilkTea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_HokkaidoMilkTea
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_HokkaidoMilkTea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_MacadamiaNutCafeLatte
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_MacadamiaNutCafeLatte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_MatchaMilkTea
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_MatchaMilkTea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Menu_PomegranateBliss
        {
            get
            {
                object obj = ResourceManager.GetObject("Menu_PomegranateBliss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
